### ISSUE TITLE
Gallery needs to hand out fresh "childPayments"

### ISSUE THREAD

**Issue by katelynsills** [Agoric/ERTP#93]
There's a bug in the current implementation in which if the faucet is tapped repeated such that all pixels have been dispersed, and those pixel payments are deposited, and the faucet is tapped again, the payments from then on are empty. This happens because in the interest of conserving the ability to create new `childPayments`, calls to `getChildPayment` return the original childPayment if it already exists. Unfortunately, if that payment has been deposited or otherwise altered, the childPayment isn't created anew, but is returned with the empty or altered amount. 

See https://github.com/Agoric/ERTP/tree/test-revoked for a simple unit test for this.

See https://github.com/Agoric/ERTP/blob/4c73a80dd6f00a9780315071d08b70945848658f/more/pixels/pixelConfig.js#L67 for the line that creates the issue.

**Comment by dtribble** [comment]
The singleton child pattern doesn't work: multiple requests for a child return the same payment, so if you transfer, revoke or otherwise consume it, then requesting "another" child will return the same, already-used payment. This is exactly what happens in tapFaucet.

There does not seem to be good motivation to allow the same child to be retrieved more than once. So instead, I propose that requesting a childPayment *always* revokes the prior child. That's more like the `claim` operation.

This would eliminate the revoke in [tapFaucet](https://github.com/Agoric/ERTP/blob/master/more/pixels/gallery.js#L189) and might eliminate the need for revokeChildren in general.

**Comment by katelynsills** [comment]
Closed by Agoric/ERTP#96

**Comment by warner** [comment]
in the old repo. this was ERTP issue 93
